export const SLECCIONAR_CLIENTE = 'SLECCIONAR_CLIENTE';
export const SLECCIONAR_PRODUCTO = 'SLECCIONAR_PRODUCTO';
export const CANTIDAD_PRODUCTOS = 'CANTIDAD_PRODUCTOS';
export const ACTUALIZAR_TOTAL = 'ACTUALIZAR_TOTAL';

